spring:
  cloud:
    gateway:
      globalcors:        corsConfigurations:
          '[/**]': 
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: 
              - Content-Type
            allowed-methods:              - GET
              - POST
              - PUT
              - DELETE 
logging:
  level:
    '[org.springframework.cloud.gateway]': INFO
    '[reactor.netty.http.client]': INFO
    